### ISSUE TITLE
Multi site interest

### ISSUE THREAD

**Issue by goldstar611** [Osirium/vcdriver#24]
Is there any interest in dropping the global variables for a class based architecture that could support multiple vcenter installations? 

There's no way to connect to multiple vcenter endpoints (as I see) since the project is using global variables (specifically _connection_obj)

**Comment by GMaxera** [comment]
I'm sorry but there is no more active development of the vcdriver

**Comment by goldstar611** [comment]
That's ok, I understand. Thanks for the quick response. Take care!
